# Generated by Django 6.0.7 on 2026-07-16 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_text', models.TextField(help_text='The text that contains the mistake')),
                ('corrected_text', models.TextField(help_text='The corrected text')),
                ('category', models.CharField(choices=[('GRAMMAR', 'Grammar'), ('SPELLING', 'Spelling'), ('VOCABULARY', 'Vocabulary'), ('PUNCTUATION', 'Punctuation')], max_length=20)),
                ('explanation', models.TextField(blank=True, help_text='The educational explanation from the AI tutor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_details', to='chats.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
