# Generated by Django 6.0.7 on 2026-07-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_taken_initial_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
