# Generated by Django 6.0.7 on 2026-07-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(default='Unknown', max_length=255)),
                ('place_type', models.CharField(max_length=100)),
                ('ai_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enriched Place',
                'verbose_name_plural': 'Enriched Places',
                'unique_together': {('name', 'city')},
            },
        ),
    ]
